### PR TITLE
Added configuration menu.

### PR DESCRIPTION
**Pull request by DrunkZebra**
This new menu provides an easy to use way to add your OpenAI key and Telegram token. A new option in the shell script runs a program that prompts for these, or you can run the Python script config.py directly if you choose. Also fixes a minor typo in the shell script.

### CODE REVIEW

**Comment by DrunkZebra** [comment]
Whether the config file is .txt or some other extension is up to you.

**Comment by DrunkZebra** [comment]
Also, the .gitignore now ignores profiles (exceptions can be made in the future but for now it's set up to ignore all .ni files) as well as the config.txt file (which will be the new place where the OpenAI key is stored).

**Comment by Deemocean** [comment]
Can you also do that for the gst.sh for under telegram? I am thinking about merging the two .sh into one but I think it would be better to keep them independent/parallel for now.

**Comment by DrunkZebra** [comment]
Done.

**Comment by Deemocean** [comment]
LGTM

**Pull request merged**
